apiVersion: skaffold/v4beta14
kind: Config
metadata:
  name: billing-service
build:
  artifacts:
    - image: billing-service
      context: .
      docker:
        dockerfile: Dockerfile
      hooks:
        before:
          - command:
              [
                "cmd",
                "/c",
                "mkdir k8s-compiled 2>nul & helm template billing-service deployments/helm/billing-service -f deployments/helm/billing-service/values.yaml > k8s-compiled/billing-service.yaml",
              ]
  local:
    push: false
manifests:
  rawYaml:
    - k8s-compiled/billing-service.yaml
deploy:
  kubectl: {}
