apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: billing-external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: envoy-secret-store
    kind: SecretStore
  target:
    name: billing-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: prod/billing-service
