// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BillingProviderUsage struct {
	ID              pgtype.UUID        `json:"id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	ChannelConfigID pgtype.UUID        `json:"channel_config_id"`
	ProviderName    string             `json:"provider_name"`
	ChannelName     string             `json:"channel_name"`
	SuccessCount    int64              `json:"success_count"`
	FailureCount    int64              `json:"failure_count"`
	ResetAt         pgtype.Timestamptz `json:"reset_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BillingSubscription struct {
	ID                     pgtype.UUID        `json:"id"`
	WorkspaceID            pgtype.UUID        `json:"workspace_id"`
	PlanID                 pgtype.UUID        `json:"plan_id"`
	PaymentProvider        string             `json:"payment_provider"`
	ExternalSubscriptionID pgtype.Text        `json:"external_subscription_id"`
	ExternalCustomerID     pgtype.Text        `json:"external_customer_id"`
	Status                 string             `json:"status"`
	ProviderMetadata       []byte             `json:"provider_metadata"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	CancelledAt            pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	Expiry3dSent           pgtype.Bool        `json:"expiry_3d_sent"`
}

type BillingUsage struct {
	ID            pgtype.UUID        `json:"id"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	ChannelName   string             `json:"channel_name"`
	CurrentUsage  int64              `json:"current_usage"`
	ResetAt       pgtype.Timestamptz `json:"reset_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Limit80Sent   pgtype.Bool        `json:"limit_80_sent"`
	Limit100Sent  pgtype.Bool        `json:"limit_100_sent"`
}

type ChannelConfig struct {
	ID pgtype.UUID `json:"id"`
}

type Environment struct {
	ID pgtype.UUID `json:"id"`
}

type Plan struct {
	ID                 pgtype.UUID `json:"id"`
	Name               string      `json:"name"`
	EmailLimitMonth    int32       `json:"email_limit_month"`
	SmsLimitMonth      int32       `json:"sms_limit_month"`
	PushLimitMonth     int32       `json:"push_limit_month"`
	SlackLimitMonth    int32       `json:"slack_limit_month"`
	WhatsappLimitMonth int32       `json:"whatsapp_limit_month"`
	WebhookLimitMonth  int32       `json:"webhook_limit_month"`
	InAppLimitMonth    int32       `json:"in_app_limit_month"`
	IsActive           bool        `json:"is_active"`
}

type Workspace struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	PlanID pgtype.UUID `json:"plan_id"`
}
