// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, name, email_limit_month, sms_limit_month, push_limit_month, slack_limit_month, whatsapp_limit_month, webhook_limit_month, in_app_limit_month, is_active
FROM public.plans
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailLimitMonth,
		&i.SmsLimitMonth,
		&i.PushLimitMonth,
		&i.SlackLimitMonth,
		&i.WhatsappLimitMonth,
		&i.WebhookLimitMonth,
		&i.InAppLimitMonth,
		&i.IsActive,
	)
	return i, err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, email_limit_month, sms_limit_month, push_limit_month, slack_limit_month, whatsapp_limit_month, webhook_limit_month, in_app_limit_month, is_active FROM public.plans 
WHERE name = $1 LIMIT 1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EmailLimitMonth,
		&i.SmsLimitMonth,
		&i.PushLimitMonth,
		&i.SlackLimitMonth,
		&i.WhatsappLimitMonth,
		&i.WebhookLimitMonth,
		&i.InAppLimitMonth,
		&i.IsActive,
	)
	return i, err
}
