// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_usage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProviderUsageByWorkspace = `-- name: GetProviderUsageByWorkspace :many
SELECT id, workspace_id, environment_id, channel_config_id, provider_name, channel_name, success_count, failure_count, reset_at, updated_at FROM billing.provider_usage
WHERE workspace_id = $1 AND environment_id = $2 AND reset_at > NOW()
`

type GetProviderUsageByWorkspaceParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) GetProviderUsageByWorkspace(ctx context.Context, arg GetProviderUsageByWorkspaceParams) ([]BillingProviderUsage, error) {
	rows, err := q.db.Query(ctx, getProviderUsageByWorkspace, arg.WorkspaceID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingProviderUsage
	for rows.Next() {
		var i BillingProviderUsage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.ChannelConfigID,
			&i.ProviderName,
			&i.ChannelName,
			&i.SuccessCount,
			&i.FailureCount,
			&i.ResetAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertProviderUsage = `-- name: UpsertProviderUsage :exec
INSERT INTO billing.provider_usage (
    workspace_id, environment_id, channel_config_id, 
    provider_name, channel_name, success_count, failure_count, reset_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (workspace_id, environment_id, provider_name, channel_name, reset_at)
DO UPDATE SET 
    success_count = billing.provider_usage.success_count + EXCLUDED.success_count,
    failure_count = billing.provider_usage.failure_count + EXCLUDED.failure_count
`

type UpsertProviderUsageParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	EnvironmentID   pgtype.UUID        `json:"environment_id"`
	ChannelConfigID pgtype.UUID        `json:"channel_config_id"`
	ProviderName    string             `json:"provider_name"`
	ChannelName     string             `json:"channel_name"`
	SuccessCount    int64              `json:"success_count"`
	FailureCount    int64              `json:"failure_count"`
	ResetAt         pgtype.Timestamptz `json:"reset_at"`
}

func (q *Queries) UpsertProviderUsage(ctx context.Context, arg UpsertProviderUsageParams) error {
	_, err := q.db.Exec(ctx, upsertProviderUsage,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.ChannelConfigID,
		arg.ProviderName,
		arg.ChannelName,
		arg.SuccessCount,
		arg.FailureCount,
		arg.ResetAt,
	)
	return err
}
