// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelActiveSubscription(ctx context.Context, workspaceID pgtype.UUID) error
	CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (pgconn.CommandTag, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (BillingSubscription, error)
	GetActiveSubscription(ctx context.Context, workspaceID pgtype.UUID) (BillingSubscription, error)
	GetExpiringSubscriptions(ctx context.Context, limit int32) ([]BillingSubscription, error)
	GetPlanByID(ctx context.Context, id pgtype.UUID) (Plan, error)
	GetPlanByName(ctx context.Context, name string) (Plan, error)
	GetProviderUsageByWorkspace(ctx context.Context, arg GetProviderUsageByWorkspaceParams) ([]BillingProviderUsage, error)
	GetUsageByChannel(ctx context.Context, arg GetUsageByChannelParams) (BillingUsage, error)
	GetUsageByWorkspace(ctx context.Context, arg GetUsageByWorkspaceParams) ([]BillingUsage, error)
	MarkExpiryEmailSent(ctx context.Context, id pgtype.UUID) error
	RenewExpiredFreeSubscription(ctx context.Context, workspaceID pgtype.UUID) (BillingSubscription, error)
	SetLimit100Sent(ctx context.Context, id pgtype.UUID) error
	SetLimit80Sent(ctx context.Context, id pgtype.UUID) error
	SyncSubscription(ctx context.Context, arg SyncSubscriptionParams) (pgconn.CommandTag, error)
	UpsertProviderUsage(ctx context.Context, arg UpsertProviderUsageParams) error
	UpsertUsage(ctx context.Context, arg UpsertUsageParams) (BillingUsage, error)
}

var _ Querier = (*Queries)(nil)
