// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subscriptions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveSubscription = `-- name: CancelActiveSubscription :exec
UPDATE billing.subscriptions
SET status = 'cancelled',
  cancelled_at = NOW()
WHERE workspace_id = $1
  AND status = 'active'
  AND current_period_end > NOW()
`

func (q *Queries) CancelActiveSubscription(ctx context.Context, workspaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, cancelActiveSubscription, workspaceID)
	return err
}

const cancelSubscription = `-- name: CancelSubscription :execresult
UPDATE billing.subscriptions
SET status = 'cancelled',
  cancelled_at = NOW()
WHERE workspace_id = $1
  AND id = $2
`

type CancelSubscriptionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, cancelSubscription, arg.WorkspaceID, arg.ID)
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO billing.subscriptions (
    workspace_id,
    plan_id,
    payment_provider,
    external_subscription_id,
    external_customer_id
  )
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, plan_id, payment_provider, external_subscription_id, external_customer_id, status, provider_metadata, current_period_start, current_period_end, cancelled_at, created_at, updated_at, expiry_3d_sent
`

type CreateSubscriptionParams struct {
	WorkspaceID            pgtype.UUID `json:"workspace_id"`
	PlanID                 pgtype.UUID `json:"plan_id"`
	PaymentProvider        string      `json:"payment_provider"`
	ExternalSubscriptionID pgtype.Text `json:"external_subscription_id"`
	ExternalCustomerID     pgtype.Text `json:"external_customer_id"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.WorkspaceID,
		arg.PlanID,
		arg.PaymentProvider,
		arg.ExternalSubscriptionID,
		arg.ExternalCustomerID,
	)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.ExternalCustomerID,
		&i.Status,
		&i.ProviderMetadata,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expiry3dSent,
	)
	return i, err
}

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT id, workspace_id, plan_id, payment_provider, external_subscription_id, external_customer_id, status, provider_metadata, current_period_start, current_period_end, cancelled_at, created_at, updated_at, expiry_3d_sent
FROM billing.subscriptions
WHERE workspace_id = $1
  AND current_period_end > NOW()
  AND status IN ('active', 'cancelled', 'past_due')
ORDER BY current_period_end DESC
LIMIT 1
`

func (q *Queries) GetActiveSubscription(ctx context.Context, workspaceID pgtype.UUID) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, getActiveSubscription, workspaceID)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.ExternalCustomerID,
		&i.Status,
		&i.ProviderMetadata,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expiry3dSent,
	)
	return i, err
}

const getExpiringSubscriptions = `-- name: GetExpiringSubscriptions :many
SELECT id, workspace_id, plan_id, payment_provider, external_subscription_id, external_customer_id, status, provider_metadata, current_period_start, current_period_end, cancelled_at, created_at, updated_at, expiry_3d_sent
from billing.subscriptions
WHERE current_period_end BETWEEN NOW()
  AND NOW() + INTERVAL '3 days'
  AND status = 'active'
  AND expiry_3d_sent = false
limit $1
`

func (q *Queries) GetExpiringSubscriptions(ctx context.Context, limit int32) ([]BillingSubscription, error) {
	rows, err := q.db.Query(ctx, getExpiringSubscriptions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingSubscription
	for rows.Next() {
		var i BillingSubscription
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.PlanID,
			&i.PaymentProvider,
			&i.ExternalSubscriptionID,
			&i.ExternalCustomerID,
			&i.Status,
			&i.ProviderMetadata,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Expiry3dSent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByExternalID = `-- name: GetSubscriptionByExternalID :one
SELECT id, workspace_id, plan_id, payment_provider, external_subscription_id, external_customer_id, status, provider_metadata, current_period_start, current_period_end, cancelled_at, created_at, updated_at, expiry_3d_sent
FROM billing.subscriptions
WHERE external_subscription_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByExternalID(ctx context.Context, externalSubscriptionID pgtype.Text) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByExternalID, externalSubscriptionID)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.ExternalCustomerID,
		&i.Status,
		&i.ProviderMetadata,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expiry3dSent,
	)
	return i, err
}

const markExpiryEmailSent = `-- name: MarkExpiryEmailSent :exec
UPDATE billing.subscriptions
SET expiry_3d_sent = true
WHERE id = $1
`

func (q *Queries) MarkExpiryEmailSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markExpiryEmailSent, id)
	return err
}

const renewExpiredFreeSubscription = `-- name: RenewExpiredFreeSubscription :one
UPDATE billing.subscriptions
SET current_period_start = NOW(),
  current_period_end = NOW() + INTERVAL '30 days'
WHERE workspace_id = $1
  AND current_period_end < NOW()
  AND payment_provider = 'system'
RETURNING id, workspace_id, plan_id, payment_provider, external_subscription_id, external_customer_id, status, provider_metadata, current_period_start, current_period_end, cancelled_at, created_at, updated_at, expiry_3d_sent
`

func (q *Queries) RenewExpiredFreeSubscription(ctx context.Context, workspaceID pgtype.UUID) (BillingSubscription, error) {
	row := q.db.QueryRow(ctx, renewExpiredFreeSubscription, workspaceID)
	var i BillingSubscription
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.PlanID,
		&i.PaymentProvider,
		&i.ExternalSubscriptionID,
		&i.ExternalCustomerID,
		&i.Status,
		&i.ProviderMetadata,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Expiry3dSent,
	)
	return i, err
}

const syncSubscription = `-- name: SyncSubscription :execresult
UPDATE billing.subscriptions
SET status = $2,
  current_period_start = $3,
  current_period_end = $4,
  cancelled_at = $5
WHERE external_subscription_id = $1
`

type SyncSubscriptionParams struct {
	ExternalSubscriptionID pgtype.Text        `json:"external_subscription_id"`
	Status                 string             `json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	CancelledAt            pgtype.Timestamptz `json:"cancelled_at"`
}

func (q *Queries) SyncSubscription(ctx context.Context, arg SyncSubscriptionParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, syncSubscription,
		arg.ExternalSubscriptionID,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelledAt,
	)
}
