// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageByChannel = `-- name: GetUsageByChannel :one
SELECT id, workspace_id, environment_id, channel_name, current_usage, reset_at, updated_at, limit_80_sent, limit_100_sent FROM billing.usage
WHERE workspace_id = $1 AND environment_id = $2 AND channel_name = $3 AND reset_at > NOW()
`

type GetUsageByChannelParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
	ChannelName   string      `json:"channel_name"`
}

func (q *Queries) GetUsageByChannel(ctx context.Context, arg GetUsageByChannelParams) (BillingUsage, error) {
	row := q.db.QueryRow(ctx, getUsageByChannel, arg.WorkspaceID, arg.EnvironmentID, arg.ChannelName)
	var i BillingUsage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.ChannelName,
		&i.CurrentUsage,
		&i.ResetAt,
		&i.UpdatedAt,
		&i.Limit80Sent,
		&i.Limit100Sent,
	)
	return i, err
}

const getUsageByWorkspace = `-- name: GetUsageByWorkspace :many
SELECT id, workspace_id, environment_id, channel_name, current_usage, reset_at, updated_at, limit_80_sent, limit_100_sent FROM billing.usage
WHERE workspace_id = $1 AND environment_id = $2 AND reset_at > NOW()
`

type GetUsageByWorkspaceParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	EnvironmentID pgtype.UUID `json:"environment_id"`
}

func (q *Queries) GetUsageByWorkspace(ctx context.Context, arg GetUsageByWorkspaceParams) ([]BillingUsage, error) {
	rows, err := q.db.Query(ctx, getUsageByWorkspace, arg.WorkspaceID, arg.EnvironmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingUsage
	for rows.Next() {
		var i BillingUsage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.EnvironmentID,
			&i.ChannelName,
			&i.CurrentUsage,
			&i.ResetAt,
			&i.UpdatedAt,
			&i.Limit80Sent,
			&i.Limit100Sent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setLimit100Sent = `-- name: SetLimit100Sent :exec
UPDATE billing.usage SET limit_100_sent = true WHERE id = $1
`

func (q *Queries) SetLimit100Sent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setLimit100Sent, id)
	return err
}

const setLimit80Sent = `-- name: SetLimit80Sent :exec
UPDATE billing.usage SET limit_80_sent = true WHERE id = $1
`

func (q *Queries) SetLimit80Sent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setLimit80Sent, id)
	return err
}

const upsertUsage = `-- name: UpsertUsage :one
INSERT INTO billing.usage (
    workspace_id, environment_id, channel_name, current_usage, reset_at
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (workspace_id, environment_id, channel_name, reset_at)
DO UPDATE SET 
    current_usage = billing.usage.current_usage + EXCLUDED.current_usage
RETURNING id, workspace_id, environment_id, channel_name, current_usage, reset_at, updated_at, limit_80_sent, limit_100_sent
`

type UpsertUsageParams struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	EnvironmentID pgtype.UUID        `json:"environment_id"`
	ChannelName   string             `json:"channel_name"`
	CurrentUsage  int64              `json:"current_usage"`
	ResetAt       pgtype.Timestamptz `json:"reset_at"`
}

func (q *Queries) UpsertUsage(ctx context.Context, arg UpsertUsageParams) (BillingUsage, error) {
	row := q.db.QueryRow(ctx, upsertUsage,
		arg.WorkspaceID,
		arg.EnvironmentID,
		arg.ChannelName,
		arg.CurrentUsage,
		arg.ResetAt,
	)
	var i BillingUsage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.EnvironmentID,
		&i.ChannelName,
		&i.CurrentUsage,
		&i.ResetAt,
		&i.UpdatedAt,
		&i.Limit80Sent,
		&i.Limit100Sent,
	)
	return i, err
}
