{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "billing-service.fullname" . }}-external-secret
  labels:
    {{- include "billing-service.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "10m" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: billing-service-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.key }}
{{- end }}
